<?php

$config_title = "Sessions";
$config_admin_user = "myadmin";
$config_default_session_size = 8;
$config_sessions_data_file = "sessions.xml";
$config_notices_file = "notices.txt";
$config_log_file = "event-log.txt";
$config_default_page_break = 5; // how often to reprint the table header

/* Colours */

$config_colour_me = "lightgreen";
$config_colour_them ="#FAAC58";
$config_colour_none = "lightpink";
$config_colour_table_header = "lightblue";
?>
